kind: pipeline
type: docker
name: pkms-release-test

trigger:
  event:
    - tag

steps:
- name: release-test-apk
  image: hao88/pkms-release:latest
  environment:
    ACCESS_TOKEN:
      from_secret: ACCESS_TOKEN
    RELEASE_URL:
      from_secret: RELEASE_URL
  commands:
  - pkms-release /drone/src/test.apk ${DRONE_TAG} my-project my-package test-apk android universal