kind: pipeline
type: docker
name: pms-releaser-test

trigger:
  event:
    - push
node:
  runner: msa2
steps:
- name: release-test-apk
  image: ghcr.io/ahaodev/pms-releaser:latest
  environment:
    ACCESS_TOKEN:
      from_secret: PMS_TOKEN
    RELEASE_URL:
      from_secret: PMS_URL
  commands:
  - pms-releaser /drone/src/test.apk ${DRONE_COMMIT} TEST Release android universal
