kind: pipeline
type: docker
name: pkms-release-test

steps:
- name: release-claude-md
  image: hao88/pkms-release:latest
  environment:
    ACCESS_TOKEN:
      from_secret: ACCESS_TOKEN
    RELEASE_URL:
      from_secret: RELEASE_URL
  commands:
  # Execute PKMS release with the following parameters:
  # - /drone/src/CLAUDE.md: Source file path (project documentation)
  # - ${DRONE_TAG}: Version from Drone CI tag (e.g., v1.0.0)
  # - CLAUDE-Guide: Artifact name for the release system
  # - markdown: Target OS/platform identifier
  # - universal: Architecture type (cross-platform compatible)
  - pkms-release /drone/src/CLAUDE.md ${DRONE_BUILD_NUMBER} CLAUDE-Guide markdown universal